spring:
  application:
    name: zuul-server

server.port: 8761

eureka:
  server:
    wait-time-in-ms-when-sync-empty: 0
  
  client:
    serviceUrl:
      defaultZone: http://eureka:admin@127.0.0.1:8761/eureka/
    register-with-eureka: false
    fetch-registry: true
  instance:
    prefer-ip-address: true

zuul:
  routes:
    main-backend:
      path: /main-backend/**
      stripPrefix: true
      serviceId: main-backend
    registration-service:
      path: /registration-service/**
      stripPrefix: true
      serviceId: registration-service

ribbon:
  eureka:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
        
