spring:
  application:
    name: zuul-server

server.port: 8761

eureka:
  server:
    wait-time-in-ms-when-sync-empty: 0
  
  client:
    serviceUrl:
      defaultZone: http://eureka:admin@127.0.0.1:8761/eureka/
    register-with-eureka: false
    fetch-registry: true
  instance:
    prefer-ip-address: true

zuul:
  routes:
    main-backend:
      path: /main-backend/**
      stripPrefix: true
      sensitive-headers:
      - Cookie, Set-Cookie
      serviceId: main-backend
    client-registration-service:
      path: /client-registration-service/**
      stripPrefix: true
      serviceId: client-registration-service
    login-service:
      path: /login-service/**
      stripPrefix: true
      serviceId: login-service
    agent-backend:
      path: /agent-backend/**
      stripPrefix: true
      sensitive-headers:
      - Cookie, Set-Cookie
      serviceId: agent-backend
    agent-creation-service:
      path: /agent-creation-service/**
      stripPrefix: true
      serviceId: agent-creation-service
    agent-login-service:
      path: /agent-login-service/**
      stripPrefix: true
      serviceId: agent-login-service   
      
      
ribbon:
  eureka:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"