//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.08 at 05:29:11 PM CEST 
//


package com.megatravel.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for additionalService.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="additionalService">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Parking"/>
 *     &lt;enumeration value="WiFi"/>
 *     &lt;enumeration value="Breakfast"/>
 *     &lt;enumeration value="Half Board"/>
 *     &lt;enumeration value="Full Board"/>
 *     &lt;enumeration value="All Inclusive"/>
 *     &lt;enumeration value="Pets Allowed"/>
 *     &lt;enumeration value="TV"/>
 *     &lt;enumeration value="Kitchen"/>
 *     &lt;enumeration value="Private Bath"/>
 *     &lt;enumeration value="Free Cancellation"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "additionalService")
@XmlEnum
public enum AdditionalService {

    @XmlEnumValue("Parking")
    PARKING("Parking"),
    @XmlEnumValue("WiFi")
    WI_FI("WiFi"),
    @XmlEnumValue("Breakfast")
    BREAKFAST("Breakfast"),
    @XmlEnumValue("Half Board")
    HALF_BOARD("Half Board"),
    @XmlEnumValue("Full Board")
    FULL_BOARD("Full Board"),
    @XmlEnumValue("All Inclusive")
    ALL_INCLUSIVE("All Inclusive"),
    @XmlEnumValue("Pets Allowed")
    PETS_ALLOWED("Pets Allowed"),
    TV("TV"),
    @XmlEnumValue("Kitchen")
    KITCHEN("Kitchen"),
    @XmlEnumValue("Private Bath")
    PRIVATE_BATH("Private Bath"),
    @XmlEnumValue("Free Cancellation")
    FREE_CANCELLATION("Free Cancellation");
    private final String value;

    AdditionalService(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AdditionalService fromValue(String v) {
        for (AdditionalService c: AdditionalService.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
