//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.14 at 06:43:02 PM CEST 
//


package com.megatravel.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.megatravel.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AgentLastName_QNAME = new QName("http://www.megatravel.com/users", "lastName");
    private final static QName _AgentFirstName_QNAME = new QName("http://www.megatravel.com/users", "firstName");
    private final static QName _AgentAddress_QNAME = new QName("http://www.megatravel.com/users", "address");
    private final static QName _AgentChats_QNAME = new QName("http://www.megatravel.com/users", "chats");
    private final static QName _AgentBRN_QNAME = new QName("http://www.megatravel.com/users", "BRN");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.megatravel.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AccommodationCategory }
     * 
     */
    public AccommodationCategory createAccommodationCategory() {
        return new AccommodationCategory();
    }

    /**
     * Create an instance of {@link Message }
     * 
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link CreateAccommodationRequest }
     * 
     */
    public CreateAccommodationRequest createCreateAccommodationRequest() {
        return new CreateAccommodationRequest();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link Agent }
     * 
     */
    public Agent createAgent() {
        return new Agent();
    }

    /**
     * Create an instance of {@link EndUser }
     * 
     */
    public EndUser createEndUser() {
        return new EndUser();
    }

    /**
     * Create an instance of {@link CreateCommentResponse }
     * 
     */
    public CreateCommentResponse createCreateCommentResponse() {
        return new CreateCommentResponse();
    }

    /**
     * Create an instance of {@link GetAccommodationTypeRequest }
     * 
     */
    public GetAccommodationTypeRequest createGetAccommodationTypeRequest() {
        return new GetAccommodationTypeRequest();
    }

    /**
     * Create an instance of {@link CreateCommentRequest }
     * 
     */
    public CreateCommentRequest createCreateCommentRequest() {
        return new CreateCommentRequest();
    }

    /**
     * Create an instance of {@link Cancelation }
     * 
     */
    public Cancelation createCancelation() {
        return new Cancelation();
    }

    /**
     * Create an instance of {@link GetAccommodationCategoryResponse }
     * 
     */
    public GetAccommodationCategoryResponse createGetAccommodationCategoryResponse() {
        return new GetAccommodationCategoryResponse();
    }

    /**
     * Create an instance of {@link GetAccommodationCategoryRequest }
     * 
     */
    public GetAccommodationCategoryRequest createGetAccommodationCategoryRequest() {
        return new GetAccommodationCategoryRequest();
    }

    /**
     * Create an instance of {@link Reservation }
     * 
     */
    public Reservation createReservation() {
        return new Reservation();
    }

    /**
     * Create an instance of {@link Comment }
     * 
     */
    public Comment createComment() {
        return new Comment();
    }

    /**
     * Create an instance of {@link PriceInSeason }
     * 
     */
    public PriceInSeason createPriceInSeason() {
        return new PriceInSeason();
    }

    /**
     * Create an instance of {@link AccommodationType }
     * 
     */
    public AccommodationType createAccommodationType() {
        return new AccommodationType();
    }

    /**
     * Create an instance of {@link CreateAccommodationResponse }
     * 
     */
    public CreateAccommodationResponse createCreateAccommodationResponse() {
        return new CreateAccommodationResponse();
    }

    /**
     * Create an instance of {@link SendMessageRequest }
     * 
     */
    public SendMessageRequest createSendMessageRequest() {
        return new SendMessageRequest();
    }

    /**
     * Create an instance of {@link SendMessageResponse }
     * 
     */
    public SendMessageResponse createSendMessageResponse() {
        return new SendMessageResponse();
    }

    /**
     * Create an instance of {@link Accommodation }
     * 
     */
    public Accommodation createAccommodation() {
        return new Accommodation();
    }

    /**
     * Create an instance of {@link GetAccommodationTypeResponse }
     * 
     */
    public GetAccommodationTypeResponse createGetAccommodationTypeResponse() {
        return new GetAccommodationTypeResponse();
    }

    /**
     * Create an instance of {@link Administrator }
     * 
     */
    public Administrator createAdministrator() {
        return new Administrator();
    }

    /**
     * Create an instance of {@link CreateReservationRequest }
     * 
     */
    public CreateReservationRequest createCreateReservationRequest() {
        return new CreateReservationRequest();
    }

    /**
     * Create an instance of {@link AdditionalServices }
     * 
     */
    public AdditionalServices createAdditionalServices() {
        return new AdditionalServices();
    }

    /**
     * Create an instance of {@link CreateReservationResponse }
     * 
     */
    public CreateReservationResponse createCreateReservationResponse() {
        return new CreateReservationResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.megatravel.com/users", name = "lastName", scope = Agent.class)
    public JAXBElement<String> createAgentLastName(String value) {
        return new JAXBElement<String>(_AgentLastName_QNAME, String.class, Agent.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.megatravel.com/users", name = "firstName", scope = Agent.class)
    public JAXBElement<String> createAgentFirstName(String value) {
        return new JAXBElement<String>(_AgentFirstName_QNAME, String.class, Agent.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Address }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.megatravel.com/users", name = "address", scope = Agent.class)
    public JAXBElement<Address> createAgentAddress(Address value) {
        return new JAXBElement<Address>(_AgentAddress_QNAME, Address.class, Agent.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Message }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.megatravel.com/users", name = "chats", scope = Agent.class)
    public JAXBElement<Message> createAgentChats(Message value) {
        return new JAXBElement<Message>(_AgentChats_QNAME, Message.class, Agent.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.megatravel.com/users", name = "BRN", scope = Agent.class)
    public JAXBElement<Integer> createAgentBRN(Integer value) {
        return new JAXBElement<Integer>(_AgentBRN_QNAME, Integer.class, Agent.class, value);
    }

}
