//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.06 at 04:10:13 PM CEST 
//


package com.example.model;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AMAgentModule complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AMAgentModule">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Accommodation" type="{http://www.megatravel.com/accommodation}Accommodation"/>
 *         &lt;element name="Message" type="{http://www.megatravel.com/message}MMessage"/>
 *         &lt;element name="ReservationComplete" type="{http://www.megatravel.com/reservation}RReservation"/>
 *         &lt;element name="Agent" type="{htttp://www.megatravel.com/users}UAgent"/>
 *         &lt;element name="id">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AMAAgentModule", namespace = "http://www.megatravel.com/agent-module", propOrder = {
    "accommodation",
    "message",
    "reservationComplete",
    "agent",
    "id"
})
public class AMAgentModule {

    @XmlElement(name = "Accommodation", required = true)
    protected Accommodation accommodation;
    @XmlElement(name = "Message", required = true)
    protected MMessage message;
    @XmlElement(name = "ReservationComplete", required = true)
    protected RReservation reservationComplete;
    @XmlElement(name = "Agent", required = true)
    protected UAgent agent;
    @XmlElement(required = true)
    protected BigInteger id;

    /**
     * Gets the value of the accommodation property.
     * 
     * @return
     *     possible object is
     *     {@link Accommodation }
     *     
     */
    public Accommodation getAccommodation() {
        return accommodation;
    }

    /**
     * Sets the value of the accommodation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Accommodation }
     *     
     */
    public void setAccommodation(Accommodation value) {
        this.accommodation = value;
    }

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link MMessage }
     *     
     */
    public MMessage getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link MMessage }
     *     
     */
    public void setMessage(MMessage value) {
        this.message = value;
    }

    /**
     * Gets the value of the reservationComplete property.
     * 
     * @return
     *     possible object is
     *     {@link RReservation }
     *     
     */
    public RReservation getReservationComplete() {
        return reservationComplete;
    }

    /**
     * Sets the value of the reservationComplete property.
     * 
     * @param value
     *     allowed object is
     *     {@link RReservation }
     *     
     */
    public void setReservationComplete(RReservation value) {
        this.reservationComplete = value;
    }

    /**
     * Gets the value of the agent property.
     * 
     * @return
     *     possible object is
     *     {@link UAgent }
     *     
     */
    public UAgent getAgent() {
        return agent;
    }

    /**
     * Sets the value of the agent property.
     * 
     * @param value
     *     allowed object is
     *     {@link UAgent }
     *     
     */
    public void setAgent(UAgent value) {
        this.agent = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

}
