//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.06 at 04:15:05 PM CEST 
//


package com.example.model;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UPerson complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UPerson">
 *   &lt;complexContent>
 *     &lt;extension base="{htttp://www.megatravel.com/users}UUser">
 *       &lt;sequence>
 *         &lt;element name="FirstName" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="LastName" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="RReservation" type="{http://www.megatravel.com/reservation}RReservation"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UPerson", propOrder = {
    "firstName",
    "lastName",
    "rReservation"
})
@Entity
@Table(name = "persons")
public class UPerson
    extends UUser implements Serializable
{

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Long id; 
	@XmlElement(name = "FirstName", required = true)
	@Column(nullable = false)
    protected String firstName;
	@XmlElement(name = "LastName", required = true)
	@Column(nullable = false)
	protected String lastName;
	@XmlElement(name = "RReservation", required = true)
	@Column(nullable = false)
    protected RReservation rReservation;

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    @Column
    public Object getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the rReservation property.
     * 
     * @return
     *     possible object is
     *     {@link RReservation }
     *     
     */
    public RReservation getRReservation() {
        return rReservation;
    }

    /**
     * Sets the value of the rReservation property.
     * 
     * @param value
     *     allowed object is
     *     {@link RReservation }
     *     
     */
    public void setRReservation(RReservation value) {
        this.rReservation = value;
    }

}
